version: '3.7'
services:
  backend:
    image: micadoproject/micado_backend
    stdin_open: true
    tty: true
    volumes:
      - type: volume
        source: backend
        target: /code
    tmpfs:
      /tmp/translations
    ports:
     - "3000:3000"
#     - "8080:8080"
#    command: /bin/sh -c "cd backend && npm start"
    command: /bin/sh -c "bash"
    environment:
      - MICADO_GIT_URL=http://test.org/
    networks:
      - micado_net
  micado_db:
    image: mdillon/postgis:11-alpine
    env_file:
      - .env
      - prod.env
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
      - type: volume
        source: postgres_init
        target: /docker-entrypoint-initdb.d
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    networks:
      - micado_net
  testnode:
    image: micadoproject/backend
    ports:
      - "3001:3000"
    networks:
      - micado_net
volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      # device is the path in the host that has to be absolute
      device: $PWD/db_data
      o: bind
  postgres_init:
    driver: local
    driver_opts:
      type: none
      # device is the path in the host that has to be absolute
      device: $PWD/db_init
      o: bind
  backend:
    driver: local
    driver_opts:
      type: none
      device: $PWD/application
      o: bind

           
networks:
  micado_net:
#    driver: bridge
    external: true